version: 2
updates:
  - package-ecosystem: pip
    directory: "/src"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    ignore:
    - dependency-name: Django
      versions:
        - "> 4.2"
  - package-ecosystem: pip
    directory: "/docs"
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: "/src"
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily