version: "3.0"

services:
  core:
    build:
      context: ../src
      dockerfile: ../docker/Dockerfile
      args:
        language: de_DE.UTF-8
        INSTALL_PLUGINS: |
          git+https://github.com/henryk/byro-fints
          git+https://github.com/henryk/byro-directdebit
    command: byro
    environment:
        PYTHONUNBUFFERED: 0
        DEVELOPMENT: 0
    networks:
      intdb: {}
      default: {}
    restart: unless-stopped
    depends_on:
      - db
    ports:
     - "8345:80"
    read_only: true
    volumes:
     - core-config:/byro/config:ro
     - core-misc:/byro/data/misc
     - core-media:/byro/data/media
     - core-logs:/byro/data/logs

  db:
    build:
      context: .
      dockerfile: ./Dockerfile-postgres
      args:
        language: de_DE
    environment:
        POSTGRES_PASSWORD: byro
        POSTGRES_DB: byro
        POSTGRES_USER: byro
        LC_MESSAGES: C
    networks:
      intdb: {}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U byro"]
      interval: 5s
      timeout: 5s
      retries: 5
    read_only: true
    tmpfs:
      - /tmp
      - /run
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  intdb:
    driver: bridge
    internal: true
  default: {}

volumes:
  core-config:
  core-misc:
  core-media:
  core-logs:
  db-data:
