web:
  build: .
  command: byro
  environment:
      PYTHONUNBUFFERED: 0
      DEVELOPMENT: 0
  links:
   - db
     #  volumes:
     #   - ..:/opt/code/
  ports:
   - "127.0.0.1:80:80"
db:
  image: postgres:12
  environment:
      POSTGRES_PASSWORD: byro
      POSTGRES_DB: byro
      POSTGRES_USER: byro
