name: byro-development

services:
  web:
    build: .
    command: "runserver 0.0.0.0:8020"
    environment:
        PYTHONUNBUFFERED: 0
        DJANGO_SETTINGS_MODULE: byro.settings
        DEVELOPMENT: 1
    entrypoint:
     - '/byro/manage.py'
    links:
     - db
    volumes:
     - .:/byro
     - ./byro.docker.cfg:/byro/byro.cfg
    ports:
     - "127.0.0.1:8020:8020"

  db:
    image: postgres:14
    environment:
        POSTGRES_PASSWORD: byro
        POSTGRES_DB: byro
        POSTGRES_USER: byro
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"

volumes:
  db-data:
