name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'

jobs:
  spelling:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('docs/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install system packages
        run: |
          sudo apt update
          sudo apt install enchant-2 hunspell aspell-en
      - name: Install Dependencies
        run: python -m pip install -Ur **/requirements.txt
      - name: Spellcheck docs
        run: make spelling
        working-directory: ./docs
      - name:
        run: '[ ! -s _build/spelling/output.txt ]'
        working-directory: ./docs

  linkcheck:
    name: Linkcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Dependencies
        run: pip3 install -Ur docs/requirements.txt
      - name: Linkcheck docs
        run: make linkcheck
        working-directory: ./docs
